[toolchain]
channel = "rve"
components = [ "rust-src", "rustfmt", "llvm-tools-preview" ]
targets = [ "thumbv6m-none-eabi", "thumbv7m-none-eabi", "thumbv8m.base-none-eabi", "thumbv8m.main-none-eabi", "riscv32emc-unknown-none-elf", "riscv32imc-unknown-none-elf", "riscv32em-unknown-none-elf", "riscv32im-unknown-none-elf" ]
